name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build

  test:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: npm test

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Setup FTP deployment
  #       uses: SamKirkland/FTP-Deploy-Action@4.0.0
  #       with:
  #         server: ${{ secrets.FTP_SERVER }}
  #         username: ${{ secrets.FTP_USERNAME }}
  #         password: ${{ secrets.FTP_PASSWORD }}
  #         local-dir: /
  #         server-dir: srv/mk-messenger-api/
